### ISSUE TITLE
Disable border

### ISSUE THREAD

**Issue by fabioselau077** [chrisedg87/flutter_rounded_loading_button#11]
How to disable border?

**Comment by chrisedg87** [comment]
Hi @fabioselau077 there isn't currently isn't an option for this but I will look it added.

**Comment by chrisedg87** [comment]
Hi @fabioselau077, when you sat the border do you essentially mean the shadow of the raised button?

**Comment by chrisedg87** [comment]
Added confutable button elevation property which when set to 0 should solve the problem. If not please re-open. v1.0.10.
