### ISSUE TITLE
Change border radius

### ISSUE THREAD

**Issue by OpticNectar** [chrisedg87/flutter_rounded_loading_button#12]
Any plans on adding an option to specify the border radius of the button?

**Comment by chrisedg87** [comment]
Sure, I'll look into this in the next release.

**Comment by chrisedg87** [comment]
Are we thinking we want the border radius to animate? As in transition to the circular loading spinner, or remain as a rounded rectangle?

**Comment by chrisedg87** [comment]
[Linked](https://github.com/chrisedg87/flutter_rounded_loading_button/tree/border-radius)

**Comment by OpticNectar** [comment]
I think it makes the most sense to transition to a circle for the loader. That seems to keep the spirit of the package and would look good, while giving more control over the initial button state look.

**Comment by chrisedg87** [comment]
Done. Fixed in v1.0.9.
