### ISSUE TITLE
Change CircleProgressIndicator size

### ISSUE THREAD

**Issue by federicodesia** [chrisedg87/flutter_rounded_loading_button#21]
Hi! very good package!

Could you add an option to resize CircleProgressIndicator?

I think with SizedBox and Center it is possible to modify the size:
`SizedBox(
      height: progressHeight,
      width: progressWidth,
      child: Center(
        child: CircularProgressIndicator()
      ),
    )`

**Comment by yasin459** [comment]
@chrisedg87  plz close issues if you fixed them(like this one)

**Comment by Abh1shekShinde** [comment]
If this issue is not yet solved ....can i have a try to fix it .

**Comment by federicodesia** [comment]
This was resolved in #23
