### ISSUE TITLE
disable button from controller

### ISSUE THREAD

**Issue by Miamoto-Musashi** [chrisedg87/flutter_rounded_loading_button#26]
is there a way to disable programmatically?
the scenario is that I have multiple buttons on the same page and I want to prevent the user to click on all of them, during the first click I would like to disable all remaining controllers

thanks

**Comment by chrisedg87** [comment]
Hi @Miamoto-Musashi, the controller is really intended to manage the animation state, so there isn't any way to disable the button that way. Disabling the button is done in the same way as the other standard buttons; by setting the onPressed function to null.
Hope that helps.
