### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by jonbhanson** [chrisedg87/flutter_rounded_loading_button#28]
Thanks for this package!  Do you plan to add null safety?

**Comment by joaovvrodrigues** [comment]
Hello, I created a PR where I applied nullsafety, updated the dependencies and removed the RaisedButton, if you want to test or use it while they don't update, just add it to your pubspec.

`  rounded_loading_button:`
`    git:`
`     url: https://github.com/joaovvrodrigues/flutter_rounded_loading_button`

![Captura de Tela 2021-03-08 às 13 22 13](https://user-images.githubusercontent.com/31359621/110349509-8b039800-8011-11eb-9d21-0631353e935b.png)

**Comment by Macacoazul01** [comment]
any updates on this?

**Comment by mi1971** [comment]
@joaovvrodrigues Hey thanks for this null safe version. Just a question...I directly substituted your button for the original one, and although my loading spinner shows...it now fails to animate the size of the button (ie shrinking down to a circle, and back to a button). It now spins, and then jumps to the small round size, and then jumps back to button size with no smooth animation. It could be something I've done, but could you confirm the animation is working for you like it does in the animated gif example? Thanks!!
![AniButton](https://user-images.githubusercontent.com/7830054/114837744-63290080-9e17-11eb-8d7f-2de3dc305492.gif)

**Comment by joaovvrodrigues** [comment]
@mi1971 Helo! Thanks for the comment, there really was this problem, it was something I missed when converting to an elevated button, but I believe I managed to fix it now. Please update and confirm for me that everything is ok!

**Comment by mi1971** [comment]
Hi @joaovvrodrigues
You got it! Thank you so much! It all seems to be working now.

**Comment by chrisedg87** [comment]
Merged PR #32 which addresses the null safety so closing this one.
