### ISSUE TITLE
Disabled

### ISSUE THREAD

**Issue by ramoneariel** [chrisedg87/flutter_rounded_loading_button#34]
How do I disabled the button now? In previous versions there was a parameter for this

**Comment by chrisedg87** [comment]
HI @ramoneariel. We didn't have a parameter to disable the button in previous versions, however disabling is done, by setting the `onPressed` parameter to `null`. Hope that helps.

**Comment by batkholboo** [comment]
The argument type 'Null' can't be assigned to the parameter type 'void Function()'.

**Comment by ramoneariel** [comment]
It does not work.

**Comment by batkholboo** [comment]
how to disable the button?. if can't be assigned to the onPressed parameter to null.

**Comment by ramoneariel** [comment]
If you set ` onPressed: () {}` the animation starts and remains loading. 
If you set to `onPressed: null` response `The argument type 'Null' can't be assigned to the parameter type 'void Function()'.`

I fixed it adding a new parameter `bool disabled` and change the line 176. `onPressed: widget.disabled ? null : _btnPressed,`

The error ocurrs because `onPressed` allway call a function, `_btnPressed` return null, but its a function.

**Comment by ramoneariel** [comment]
line 176.          `onPressed: widget.onPressed == null ? null : _btnPressed,`

**Comment by chrisedg87** [comment]
Sorry yes, this is definitely an issue since adding the null safety. @ramoneariel are you up for raising a PR for that one?

**Comment by ramoneariel** [comment]
I try to fix the problem with the disabled color, because it doesn't change color, only remove elevation

**Comment by ramoneariel** [comment]
Ok, i found the error in my main theme, not in the widget

**Comment by chrisedg87** [comment]
Fixed in version 2.0.4

**Comment by batkholboo** [comment]
Thanx @chrisedg87  @ramoneariel.
