### ISSUE TITLE
disabling button from controller

### ISSUE THREAD

**Issue by ramoneariel** [chrisedg87/flutter_rounded_loading_button#41]
Hi, I added a disable status  to manage from controller.

**Comment by chrisedg87** [comment]
Hi @ramoneariel this doesn't sound like an issue. Did you mean to raise a PR?

**Comment by ramoneariel** [comment]
Hi, sorry, i cant push my branch and i dont know how to ask for permision.

**Comment by chrisedg87** [comment]
Have a look here https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
