### ISSUE TITLE
Initialize RoundedLoadingButtonController listeners in build() not in initState()

### ISSUE THREAD

**Issue by hagar-yasser** [chrisedg87/flutter_rounded_loading_button#42]
This will solve the problem in issue #14.

The problem happens every time the widget that holds the controller changes (so the controller itself changes). The problem occurs because some fields in the controller gets initialized only one time in the initState of the RoundedLoadingButton, so when the controller changes but the state doesn't change, the fields don't get initialized.

**Comment by chrisedg87** [comment]
Hi @hagar-yasser, did you mean to raise this as a pull request?
