### ISSUE TITLE
Get current button state

### ISSUE THREAD

**Issue by bemesquita** [chrisedg87/flutter_rounded_loading_button#45]
I am trying to get the current state of the button. Is there a functionality for that?

**Comment by chrisedg87** [comment]
Hi @bemesquita, there isn't currently a way to get the current state, although sounds like something we might want to add.

**Comment by bemesquita** [comment]
Thanks Chris, just faced a scenario that I wanted to hide a few components when button is loading. I will fork the repo and see how this can be easily done and keep you updated. Cheers!

**Comment by appa204544** [comment]
@chrisedg87 Any update on this?

**Comment by chrisedg87** [comment]
I've added two new properties to the button controller - `stateStream` allows you to subscribe and listen to even changes, and `currentState` will return the current state of the button, both in the forms of the `ButtonState` enum.

**Comment by appa204544** [comment]
@chrisedg87 Thank you. Really appreciate. I was in the middle of a project and waiting for this update. :+1:
